# Generated by Django 3.2.18 on 2023-03-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parents_Name', models.CharField(max_length=500)),
                ('home_address', models.CharField(max_length=500, null=True)),
                ('contact_number', models.CharField(max_length=90, null=True)),
                ('delivery_date', models.CharField(max_length=150, null=True)),
                ('date_of_naming_ceremony', models.CharField(max_length=250, null=True)),
                ('place_of_naming_ceremony', models.CharField(max_length=450, null=True)),
                ('father_Band_Name', models.CharField(choices=[('NIL', 'NIL'), ('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], default='SM', max_length=20)),
                ('mother_Band_Name', models.CharField(choices=[('NIL', 'NIL'), ('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], default='RH', max_length=20)),
                ('father_unit_name', models.CharField(max_length=90, null=True)),
                ('mother_unit_name', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Parent_Name', models.CharField(max_length=500)),
                ('child_First_Name', models.CharField(max_length=200)),
                ('father_Band_Name', models.CharField(choices=[('NIL', 'NIL'), ('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], default='SM', max_length=20)),
                ('mother_Band_Name', models.CharField(choices=[('NIL', 'NIL'), ('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], default='RH', max_length=20)),
                ('father_unit_name', models.CharField(max_length=90, null=True)),
                ('mother_unit_name', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarriageThanksgiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=1000)),
                ('band_of_husband', models.CharField(choices=[('NIL', 'NIL'), ('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], default='J', max_length=350)),
                ('band_of_wife', models.CharField(choices=[('NIL', 'NIL'), ('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], default='RH', max_length=350)),
                ('date_of_marriage', models.DateTimeField(auto_now_add=True)),
                ('father_unit_name', models.CharField(max_length=90, null=True)),
                ('mother_unit_name', models.CharField(max_length=90, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
