# Generated by Django 3.2 on 2023-01-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageThanksgiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=1000)),
                ('band_of_husband', models.CharField(max_length=350)),
                ('band_of_wife', models.CharField(max_length=350)),
                ('date_of_marriage', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
