# Generated by Django 3.2 on 2023-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriagethanksgiving',
            name='band_of_husband',
            field=models.CharField(choices=[('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], max_length=350),
        ),
        migrations.AlterField(
            model_name='marriagethanksgiving',
            name='band_of_wife',
            field=models.CharField(choices=[('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], max_length=350),
        ),
    ]
