# Generated by Django 3.2.18 on 2023-03-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_marriagethanksgiving_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marriagethanksgiving',
            name='time_stamp',
        ),
    ]
