# Generated by Django 3.2 on 2023-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20230202_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriagethanksgiving',
            name='band_of_husband',
            field=models.CharField(choices=[('NIL', 'NIL'), ('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], default='J', max_length=350),
        ),
        migrations.AlterField(
            model_name='marriagethanksgiving',
            name='band_of_wife',
            field=models.CharField(choices=[('NIL', 'NIL'), ('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], default='RH', max_length=350),
        ),
    ]
