# Generated by Django 3.2.18 on 2023-03-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_remove_marriagethanksgiving_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdedication',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
