# Generated by Django 3.2 on 2023-02-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20230202_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=500)),
                ('child_first_name', models.CharField(max_length=200)),
                ('child_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_band_name', models.CharField(choices=[('NIL', 'NIL'), ('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], default='SM', max_length=20)),
                ('mother_band_name', models.CharField(choices=[('NIL', 'NIL'), ('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], default='RH', max_length=20)),
            ],
        ),
    ]
