# Generated by Django 3.2 on 2023-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_birthnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthnotification',
            name='child_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
