# Generated by Django 3.2.18 on 2023-03-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_childdedication_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdedication',
            name='mother_Band_Name',
            field=models.CharField(choices=[('NIL', 'NIL'), ('RHODA', 'RHODA'), ('HEPZIBAH', 'HEPZIBAH'), ('FAITH', 'FAITH'), ('SUSANNAH', 'SUSANNAH'), ('JOANA', 'JOANA'), ('TRUTH DIVINE', 'TRUTH DIVINE')], default='RH', max_length=20),
        ),
    ]
