# Generated by Django 3.2.18 on 2023-03-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_childdedication_mother_band_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdedication',
            name='father_Band_Name',
            field=models.CharField(choices=[('NIL', 'NIL'), ('JOSEPH', 'JOSEPH'), ('JEREMIAH', 'JEREMIAH'), ('EPHRAIM', 'EPHRAIM'), ('ST.MARK', 'ST.MARK'), ('ST.JOHN', 'ST.JOHN'), ('JAMES', 'JAMES')], default='SM', max_length=20),
        ),
    ]
