# Generated by Django 3.2 on 2023-02-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_birthnotification_child_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthnotification',
            old_name='child_first_name',
            new_name='child_First_Name',
        ),
        migrations.RenameField(
            model_name='birthnotification',
            old_name='child_last_name',
            new_name='child_Last_Name',
        ),
        migrations.RenameField(
            model_name='birthnotification',
            old_name='child_middle_name',
            new_name='child_Middle_Name',
        ),
        migrations.RenameField(
            model_name='birthnotification',
            old_name='family_name',
            new_name='family_Name',
        ),
        migrations.RenameField(
            model_name='birthnotification',
            old_name='father_band_name',
            new_name='father_Band_Name',
        ),
        migrations.RenameField(
            model_name='birthnotification',
            old_name='mother_band_name',
            new_name='mother_Band_Name',
        ),
    ]
