# Generated by Django 3.2 on 2023-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20230202_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthnotification',
            name='child_Last_Name',
            field=models.CharField(max_length=200),
        ),
    ]
