# Generated by Django 3.2 on 2023-02-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_alter_birthnotification_child_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_Name', models.CharField(max_length=500)),
                ('child_First_Name', models.CharField(max_length=200)),
                ('child_Middle_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('child_Last_Name', models.CharField(max_length=200)),
                ('father_Band_Name', models.CharField(choices=[('NIL', 'NIL'), ('J', 'JOSEPH'), ('JE', 'JEREMIAH'), ('EP', 'EPHRAIM'), ('SM', 'ST.MARK'), ('SJ', 'ST.JOHN'), ('JA', 'JAMES')], default='SM', max_length=20)),
                ('mother_Band_Name', models.CharField(choices=[('NIL', 'NIL'), ('RH', 'RHODA'), ('HZ', 'HEPZIBAH'), ('FT', 'FAITH'), ('SU', 'SUSANNAH'), ('JO', 'JOANA'), ('TD', 'TRUTH DIVINE')], default='RH', max_length=20)),
                ('father_unit_name', models.CharField(max_length=90, null=True)),
                ('mother_unit_name', models.CharField(max_length=90, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='father_unit_name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='mother_unit_name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='marriagethanksgiving',
            name='father_unit_name',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='marriagethanksgiving',
            name='mother_unit_name',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
