# Generated by Django 3.2 on 2023-02-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20230205_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthnotification',
            old_name='family_Name',
            new_name='Parents_Name',
        ),
        migrations.RenameField(
            model_name='childdedication',
            old_name='family_Name',
            new_name='Parent_Name',
        ),
        migrations.RemoveField(
            model_name='birthnotification',
            name='child_First_Name',
        ),
        migrations.RemoveField(
            model_name='birthnotification',
            name='child_Last_Name',
        ),
        migrations.RemoveField(
            model_name='birthnotification',
            name='child_Middle_Name',
        ),
        migrations.RemoveField(
            model_name='childdedication',
            name='child_Last_Name',
        ),
        migrations.RemoveField(
            model_name='childdedication',
            name='child_Middle_Name',
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='contact_number',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='date_of_naming_ceremony',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='home_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='birthnotification',
            name='place_of_naming_ceremony',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='childdedication',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
