# Generated by Django 3.2 on 2023-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_auto_20230206_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdedication',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
