# Generated by Django 3.2 on 2023-02-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_alter_childdedication_date_of_dedication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdedication',
            name='date_of_dedication',
        ),
    ]
