# Generated by Django 4.1 on 2023-02-16 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_remove_childdedication_date_of_dedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdedication',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
