# Generated by Django 4.1 on 2023-02-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_alter_childdedication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdedication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
